from django.conf.urls.defaults import *
from checkin.views import check_in
from tokenapi.decorators import token_required
from views import *

urlpatterns = patterns('',
    url(r'^get_topics_list/$', get_topics_list),
    url(r'^get_topics_list/(?P<forum_id>\d+)/$', get_topics_list),
    url(r'^get_topics_list/(?P<forum_id>\d+)/(?P<type_id>\d+)/$', get_topics_list),
    url(r'^topicinfo/(?P<tid>\d+)/$', view_topic),
    url(r'^topiccomments/(?P<tid>\d+)/$', get_topic_comments),
    url(r'^topiccomments2/(?P<tid>\d+)/$', get_topic_comments2),
    url(r'^get_games_list2/$', get_games_list),
    url(r'^get_emu_games_list/$', get_emu_games_list),
    url(r'^get_hot_games_list2/$', get_hot_games_list),
    url(r'^get_games_tag/(?P<game_tag>[^/]+)/$', get_games_tag),
    url(r'^game_timely_refresh/(?P<gid>\d+)/$', game_timely_refresh),
    url(r'^gameinfo/(?P<package>\S+)/$', view_game),
    url(r'^view_emu_game/(?P<game_code>\S+)/$', view_emu_game),
    url(r'^gamecomments/(?P<package>\S+)/$', get_game_comments),
    url(r'^get_games_setting/(?P<package>[^/]+)/$', get_games_setting),
    url(r'^game_qhh_rank/$', game_qhh_rank),
    url(r'^focus/$', focus),
    url(r'^game_qhh/(?P<game_id>\d+)/$', game_qhh),
    url(r'^check_update/$', check_update),
    url(r'^user_info/$', user_info),
    url(r'^post_comment/$', post_comment),
    url(r'^post_reply/$', post_reply),
    url(r'^post_topic/$', post_topic),
    url(r'^register/$', register),
    url(r'^sleep/$', sleep),
    url(r'^gallery/$', gallery),
    url(r'^get_gallerys_tag/(?P<gallery_tag>[^/]+)/$', get_gallerys_tag),
    url(r'^forums_info/$', forums_info),
    url(r'^checkin/$', token_required(check_in)),
    url(r'^wandoujia/$', wandoujia),
    url(r'^apps/$', apps),
    url(r'^emoji/$', get_emoji),
    url(r'^check_game_install/$', check_game_install),
    url(r'^spider_wdj/(?P<package>\S+)/$', spider_wdj),

    url(r'^author/(?P<user_id>\d+)/$', author),
    url(r'^schema/$', schema),
    url(r'^sync/$', sync),
    url(r'^commend/$', commend),
    url(r'^flowinfo/(?P<fid>\d+)/$', flowinfo),
    url(r'^flows_sticky_list/$', flows_sticky_list),
    url(r'^flows_sticky_list/(?P<column_name>\w+)/$', flows_sticky_list),
    url(r'^flow_list/(?P<column_name>\w+)/$', flow_list),
    url(r'^flow_list_date/(?P<date>\S+)/$', flow_list_date),
    url(r'^flow_list_tag/(?P<tag>\S+)/$', flow_list_tag),
    url(r'^flow_related_list/(?P<flow_id>\w+)/$', flow_related_list),
    url(r'^subs/(?P<user_id>\d+)/$', subs),
    url(r'^unsubs/(?P<user_id>\d+)/$', unsubs),
    url(r'^subs_tag/(?P<tag_name>\w+)/$', subs_tag),
    url(r'^unsubs_tag/(?P<tag_name>\w+)/$', unsubs_tag),
    url(r'^subs_list/$', subs_list),

    url(r'^change_avatar/$', change_avatar),
    url(r'^comment_list/$', comment_list),
    url(r'^comment_positive/(?P<comment_id>\d+)/$', comment_positive),
    url(r'^gift_exchange/(?P<gift_id>\d+)/$', gift_exchange),
    url(r'^gift_inquire/(?P<package>\S+)/$', gift_inquire),
    url(r'^bili_api_url/(?P<flow_id>\d+)/$', bili_api_url),

    url(r'^coll/(?P<target_id>\d+)/$', coll),
    url(r'^uncoll/(?P<target_id>\d+)/$', uncoll),
    url(r'^coll_list/$', coll_list),

    url(r'^game_search/$', game_search),
    url(r'^topic_search/$', topic_search),
    url(r'^flow_search/$', flow_search),

    url(r'^get_notification_num/$', get_notification_num),
    url(r'^get_notification_list/(?P<type>\w+)/$', get_notification_list),
    (r'', include('tokenapi.urls')),
)
